---
# - name: Start Kafka
#   docker_container:
#     name: kafka

# - name: Restart Harbor
#   docker_container:
#     name: harbor
#     state: started
#     restart: true
#   loop: "{{ docker_images.stdout_lines }}"