harbor_offline_installer_version: "v2.7.3"
harbor_offline_installer_tar_file: "harbor-offline-installer-{{ harbor_offline_installer_version }}.tgz"
harbor_offline_installer_url: "https://github.com/goharbor/harbor/releases/download/{{ harbor_offline_installer_version }}/{{ harbor_offline_installer_tar_file }}"

harbor_home_dir: "/opt"
harbor_tar_file: "{{ harbor_home_dir }}/{{ harbor_offline_installer_tar_file }}"