---
k8s_version: "1.31"
k8s_pod_network_cidr: "10.244.0.0/16"
k8s_apiserver_advertise_address: "10.0.20.41"
k8s_control_plane_node_name: "k8s-node-01"
flannel_manifest_url: "https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml"
ingress_nginx_manifest_url: "https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.11.2/deploy/static/provider/baremetal/deploy.yaml"
ingress_nginx_nodeport_http: 30080
ingress_nginx_nodeport_https: 30443
k8s_kubeconfig_local_dest: "../artifacts/kubeconfig-k8s"
