---
http:
  routers:
    gitlab-router:
      rule: Host(`gitlab.damoreira.ml`)
      service: gitlab
      tls:
        certResolver: letsencrypt
  services:
    gitlab:
      loadBalancer:
        servers:
        - url: http://10.0.20.3:80