---
http:
  routers:
    harbor-router:
      rule: Host(`harbor.damoreira.ml`)
      service: harbor
      tls:
        certResolver: letsencrypt
  services:
    harbor:
      loadBalancer:
        servers:
        - url: http://10.0.20.4:80