---
http:
  routers:
    suwayomi-router:
      rule: Host(`mangareader.damoreira.ml`)
      service: suwayomi
  services:
    suwayomi:
      loadBalancer:
        servers:
        - url: http://10.0.5.2:4567