---
http:
  routers:
    torrent-router:
      rule: Host(`torrent.damoreira.ml`)
      service: torrent
  services:
    torrent:
      loadBalancer:
        servers:
        - url: http://10.0.0.20:9091/