---
- import_playbook: ./playbooks/traefik.yml
- import_playbook: ./playbooks/kuma.yml
- import_playbook: ./playbooks/kafka.yml
- import_playbook: ./playbooks/plex.yml
- import_playbook: ./playbooks/harbor.yml
- import_playbook: ./playbooks/suwayomi.yml
- import_playbook: ./playbooks/coder.yml
- import_playbook: ./playbooks/pihole.yml
- import_playbook: ./playbooks/sso.yml
- import_playbook: ./playbooks/jellyfin.yml
- import_playbook: ./playbooks/ghost.yml
