---
- name: Restart Docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
    daemon_reload: true

- name: Restart Suwayomi
  community.docker.docker_compose_v2:
    project_src: "{{ suwayomi_compose_dir }}"
    state: restarted